spring.application.name=projectlogin
# 1. Configuración de la conexión física a tu MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/projectlogin_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Tsla3327
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Estrategia de JPA / Hibernate
# 'update' le dice a Spring: "Si la tabla no existe en MySQL, créala automáticamente"
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de Java las consultas SQL reales que se están ejecutando
spring.jpa.show-sql=true